package app.tracktune.utils;

/**
 * Dedicated class for localizing strings
 */
public class Strings {
    public static final String ERROR = "Error";
    public static final String SUCCESS = "Success";
    public static final String LOGIN_FAILED = "Login failed";
    public static final String USER_PWD_EMPTY = "Username or password is empty";
    public static final String FIELD_EMPTY = "One or more fields are empty";
    public static final String CONN_FAILED = "Connection failed";
    public static final String DB_CONN_FAILED = "Connection with database failed";
    public static final String ERR_EXEC_STMT = "Error executing statement ";
    public static final String ERR_INIT_DB = "Error initializing database";
    public static final String ERR_REQUEST_ALREADY_EXISTS = "User already exists";
    public static final String ERR_USER_NOT_FOUND = "User not found";
    public static final String GENRE_FAILED = "Genre failed";
    public static final String MUSICAL_INSTRUMENT_FAILED = "Musical Instrument failed";
    public static final String AUTHOR_FAILED = "Author failed";
    public static final String ERR_GENERAL = "Something went wrong";
    public static final String MEDIA_ERROR = "Media error";
    public static final String MEDIA_NOT_SUPPORTED = "Media type not supported";
    public static final String ERR_ACCOUNT_REQUEST = "Account request failed";
    public static final String ERR_ENTITY_ALREADY_EXISTS = "There is already an element of this entity";
    public static final String ERR_USER_NOT_ALLOWED = "User not allowed";
    public static final String ERR_SQL_INJECTION = "SQL injection detected";
    public static final String ERR_GENRE_ALREADY_EXISTS = "Genre already exists";
    public static final String ERR_MUSICAL_INSTRUMENT_ALREADY_EXISTS = "Musical instrument already exists";
    public static final String ERR_GENRE_NOT_FOUND = "Genre not found";
    public static final String ERR_AUTHOR_ALREADY_EXISTS = "Author already exists";
    public static final String ACCEPT = "Accept";
    public static final String RESTORE = "Restore";
    public static final String REJECT = "Reject";
    public static final String DELETE = "Delete";
    public static final String EDIT = "Edit";
    public static final String SAVE = "Save";
    public static final String VIEW = "View";
    public static final String TRACKS = "Tracks:";
    public static final String AUTHORS = "Author:";
    public static final String GENRES = "Genres:";
    public static final String INSTRUMENTS = "Instruments:";
    public static final String FILE_FORMAT = "File format:";
    public static final String RESOURCE_SIZE = "Resource Size:";
    public static final String DURATION = "Duration:";
    public static final String REGISTERED_DATA = "Registered Data:";
    public static final String LINKED_RESOURCES = "Linked Resources";
    public static final String CANCEL = "Cancel";
    public static final String USER = "USER";
    public static final String EMPTY_LIST = "No elements found";
    public static final String ERR_LOAD_FILE = "Error loading file";
    public static final String ERR_FILE_NOT_FOUND = "File not found";
    public static final String ERR_DATABASE = "Database error";
    public static final String RESULT = "Result";
    public static final String RESOURCE_UPLOADED = "Resource uploaded successfully";
    public static final String RESOURCE_UPDATED = "Resource updated successfully";
    public static final String RESOURCE_NOT_UPLOADED = "Resource not uploaded";
    public static final String MAKE_ADMIN = "Make Admin";
    public static final String SUSPEND = "Suspend";
    public static final String ERR_ME = "Me error";
    public static final String ADMIN = "ADMIN";
    public static final String ERR_ENTITY_NOT_FOUND = "Entity not found";
    public static final String ERR_USER_ALREADY_EXISTS = "User already exists";
    public static final String CONFIRM_DELETION = "Confirm deletion";
    public static final String ARE_YOU_SURE = "Are you sure to complete this operation?";
    public static final String CHANGE_PRIVILEGES = "Change privileges";
    public static final String ERR_DELETE_TRACK = "Error to deleting track";
    public static final String REPLY_TO_COMMENT = "Reply to comment";
    public static final String WRITE_YOUR_REPLY = "Write your reply";
    public static final String REPLIES = "[replies]";
    public static final String HIDE_REPLIES = "[hide replies]";
}
